# Generated by Django 2.2.3 on 2019-07-21 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Haraj_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='Manufacturer',
            field=models.CharField(default='manufacture', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='picture',
            field=models.ImageField(default='https://bmw.grandprixmotors.com/wp-content/uploads/2018/01/BMW_MY18_MSeries_M5_Gallery_04.jpg', upload_to='items'),
            preserve_default=False,
        ),
    ]
