# Generated by Django 2.2.3 on 2019-07-24 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Haraj_app', '0003_userprofil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='city',
            field=models.CharField(choices=[('D', 'Dammam'), ('J', 'Jeddah'), ('R', 'Riyadh')], max_length=1),
        ),
    ]
